### PR TITLE
Add HI code to main block

### LINKED ISSUE #34: Real-world data with method block code in main block
We get lots of total soundings files that contain the `HI` code in the main block ($):

```
$
HD=20210324,HI=004940,HM=24
#
D=0.025,A=1.096
D=0.050,A=1.096
D=0.075,A=1.096
...
```

In the SGF standard, the `HI` code is only defined for the method block (€ or £). 

Our problem is that this code `HI` (undefined for the main block) is returned as an integer (4940) that sort of garbles the data for us (leading zeros removed).

A solution for us is to add the `HI` code to the `/libsgfdata/main.csv` and also add a converter function for this time string.  

I am trying to get a name for the source of these files so they also can be added to the main code file.

Do you think this is something you would accept a PR for?

### PR DESCRIPTION
**Pull request by josteinl**
- Add HI code to main block (with source geotechab).
- Add test and test data for row with `HI` code (start time).
- Add conversion function for the type `time` that return a `datetime.time()` object. 
- Change the type for the code `AD` from `time` to `seconds`. 
- Change the type for the code `%` from `time` to `milliseconds` .
- Add placeholders for conversion functions for `seconds` and `milliseconds`.
- Bump version number to '0.0.15-beta.2'

I am not totally sure how the normalization work, and if I am missing something. Looks like the code `%` is referencing the code `AD` that has different units (milliseconds and seconds) in the file `libsgfdata\data.csv`.

Fix #34

### CODE REVIEW

**Comment by redhog** [comment]
I'm happy to include the addition to HI parsing, but sceptical of how AD is parsed here:
The unit of AD is seconds, with a format of figure according to SGF, which I interpret as just an integer or float, of number of seconds since midnight.
Do you have files from the wild indicating that these should be interpreted as HHMMSS?

I suggest a separate type of "time_seconds" or something similar, that converts to / from datetime.time, but with a format that's just seconds from midnight, and use that for AD (but not for HI).

This would also mean that adding a normalization of HI to AD would work as expected...

**Comment by josteinl** [comment]
> I'm happy to include the addition to HI parsing, but sceptical of how AD is parsed here: The unit of AD is seconds, with a format of figure according to SGF, which I interpret as just an integer or float, of a number of seconds since midnight. Do you have files from the wild indicating that these should be interpreted as HHMMSS?

I did not change how the code `AD` is parsed, just renamed its type from `time` to `seconds`, since the unit for AD is seconds. Then I resued the name `time` for my new code `HI` parsing it as HHMMSS or HHMM returning a `datetime.time()` object.

But on the last line of  `libsgfdata/data.csv` there is a definition of a code `%`, that I think is referencing the`AD` code in the last column. Here I think there may be a problem since it seems that the unit for code `%` is milliseconds and not seconds as for `AD`.

**Comment by redhog** [comment]
Right... I think I did some plotting of this some year ago actually, and concluded the same - the offset isn't since epoch, it's always some 20mins or so before drilling begins... Startup of the machine maybe?

**Comment by josteinl** [comment]
> Right... I think I did some plotting of this some year ago actually, and concluded the same - the offset isn't since epoch, it's always some 20mins or so before drilling begins... Startup of the machine maybe?

That was one of my thoughts as well, that it was some time counter since machine startup.

**Pull request merged**
